#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>       // close()
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "sockhelper.h"
#include <netdb.h>
#include <pthread.h>
#include <semaphore.h>



/* Recommended max object size */
#define MAX_OBJECT_SIZE 102400

static const char *user_agent_hdr = "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0";

int complete_request_received(char *);
void parse_request(char *, char *, char *, char *, char *);
void test_parser();
void print_bytes(unsigned char *, int);
int open_sf(int port);
void handle_client(int client_fd);
void *multi_thread(void *arg);
void enqueue(int client_fd);
int dequeue(void);

int queue[5];
int front = 0;          
int rear = 0; 
int count = 0;   
pthread_mutex_t queue_mutex = PTHREAD_MUTEX_INITIALIZER;
sem_t empty_slots;   // initially QUEUE_SIZE
sem_t filled_slots;  // initially 0

int main(int argc, char *argv[])
{
	//test_parser(); ,
	printf("%s\n", user_agent_hdr);
	int port = atoi(argv[1]);
	int server_fd = open_sf(port);
	printf("listening on port %d...\n", port);

	pthread_t tid;
	sem_init(&empty_slots, 0, 5); 
	sem_init(&filled_slots, 0, 0); 

	for (int i = 0; i < 8; i++){
		pthread_create(&tid, NULL, multi_thread, NULL);
	}

	while (1){
		struct sockaddr_in client_addr;
		socklen_t client_len = sizeof(client_addr);
		int client_fd = accept(server_fd, (struct sockaddr*)&client_addr, &client_len);
		enqueue(client_fd);

		printf("Accepted a client on socket %d\n", client_fd);
	}
}

int complete_request_received(char *request) {
	if (strstr(request, "\r\n\r\n") == NULL) return 0;
	else return 1;
}

void *multi_thread(void *arg){
	while (1){
		int client_fd = dequeue();
		handle_client(client_fd);
		close(client_fd);
	}
}

void enqueue(int client_fd){
	sem_wait(&empty_slots);                
    pthread_mutex_lock(&queue_mutex);      

    queue[rear] = client_fd;               
    rear = (rear + 1) % 5;

    pthread_mutex_unlock(&queue_mutex);    
    sem_post(&filled_slots); 
}

int dequeue() {
    sem_wait(&filled_slots);             
    pthread_mutex_lock(&queue_mutex);      

    int client_fd = queue[front];
    front = (front + 1) % 5;

    pthread_mutex_unlock(&queue_mutex);   
    sem_post(&empty_slots);               
    return client_fd;
}

/*
    parse_request() was generated by ChatGPT (GPT-5.1)

	Prompt:
	"Can you generate a parse_requests() function that takes the following in as arguments:

	char *request: a (null-terminated) string containing an HTTP request.
	char *method: a string to which the method, extracted from the request, is copied.
	char *hostname: a string to which the hostname, extracted from the URL, is copied.
	char *port: a string to which the port, extracted from the URL, is copied. If no port is specified in the URL, then it should be populated with "80", the default port for HTTP.
	char *path: a string to which the path, extracted from the URL, is copied. The path should include not only the file path, but also the query string, if any.

	I need this parse_requests() function to parse the "request method", which are all characters from the beginning of the request up until the first space. Then I need it to parse the URL, which starts with the first character after the fist space until the second space. Finally it needs to parse the header, which is all the characters after the first line (after the \r\n sequence).

	For the URL, if there is a colon ":" that comes AFTER the "://" then the digits immediately following is the PORT number. The characters in between the "://" and the colon for the port number is the hostname. All characters after the port number are the path.

	If there is not a colon after "://", meaning the port number is not specified, then use port 80. In this case the hostname is made up of the characters between "://" and the next forward slash "/", and all character after the hostname are the path.

	Thanks!"

	Changes: I didn't have to change anything, it works (so far).
*/
void parse_request(char *request, char *method,
                   char *hostname, char *port, char *path)
{
    char *start, *end;

    /* ---------------------------------------------------------
       1. Extract METHOD  (everything before first space)
       --------------------------------------------------------- */
    start = request;
    end = strstr(start, " ");   // end of method
    strncpy(method, start, end - start);
    method[end - start] = '\0';

    /* ---------------------------------------------------------
       2. Extract the URL (between first and second space)
       --------------------------------------------------------- */
    start = end + 1;            // start of URL
    end = strstr(start, " ");   // end of URL

    char url[256];
    strncpy(url, start, end - start);
    url[end - start] = '\0';

    /* ---------------------------------------------------------
       3. Inside the URL, skip "http://"
       --------------------------------------------------------- */
    char *url_start = strstr(url, "://");
    if (url_start == NULL) {
        // Should not happen for this lab, but fallback
        url_start = url;
    } else {
        url_start += 3; // move past ://
    }

    /* ---------------------------------------------------------
       4. Check for a port number in the URL
       --------------------------------------------------------- */
    char *colon = strchr(url_start, ':');
    char *slash = strchr(url_start, '/');  // start of path

    if (colon != NULL && colon < slash) {
        /* ---------------------------------------
           Case 1: Port IS specified (hostname:port/path)
           --------------------------------------- */

        // HOSTNAME: from url_start up to colon
        strncpy(hostname, url_start, colon - url_start);
        hostname[colon - url_start] = '\0';

        // PORT: digits after colon up to slash
        strncpy(port, colon + 1, slash - (colon + 1));
        port[slash - (colon + 1)] = '\0';
    } else {
        /* ---------------------------------------
           Case 2: Port NOT specified
           --------------------------------------- */
        strcpy(port, "80");  // default port

        // HOSTNAME: from url_start up to slash
        strncpy(hostname, url_start, slash - url_start);
        hostname[slash - url_start] = '\0';
    }

    /* ---------------------------------------------------------
       5. PATH is everything from the "/" onward
       --------------------------------------------------------- */
    strcpy(path, slash);  // includes query string if present
}


int open_sf(int port){

	int sockfd = socket(AF_INET, SOCK_STREAM, 0);
	int optval = 1;
	setsockopt(sockfd, SOL_SOCKET, SO_REUSEPORT, &optval, sizeof(optval));
	struct sockaddr_in addr;

    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port);  

	bind(sockfd, (struct sockaddr *)&addr, sizeof(addr));
	listen(sockfd, 10);
	return sockfd;
}

void handle_client(int client_fd){
	char req_buffer[1024]; 
	req_buffer[0] = '\0';
	int bytes_read = 0;
	int n = 0;
	char method[16], hostname[64], port[8], path[256];
	while (complete_request_received(req_buffer) == 0){
		n = recv(client_fd, req_buffer + bytes_read, 1024 - bytes_read, 0);
		if (n < 0){
			close(client_fd);
			return;
		}else if (n == 0) {
            break;
        }
		bytes_read += n;
        req_buffer[bytes_read] = '\0';
		if (complete_request_received(req_buffer)) break;
	}

	req_buffer[bytes_read] = '\0';
	parse_request(req_buffer, method, hostname, port, path);
	print_bytes((unsigned char *)req_buffer, bytes_read);
	printf("METHOD: %s\n", method);
	printf("HOSTNAME: %s\n", hostname);
	printf("PORT: %s\n", port);
	printf("PATH: %s\n", path);
	
	char request[1024];

	sprintf(request, "%s %s HTTP/1.0\r\n", method, path);

	if (strcmp(port, "80") == 0) sprintf(request + strlen(request), "Host: %s\r\n", hostname);
	else sprintf(request + strlen(request), "Host: %s:%s\r\n", hostname, port);

	sprintf(request + strlen(request),"%s\r\n", user_agent_hdr);
	sprintf(request + strlen(request), "Connection: close\r\n");
	sprintf(request + strlen(request), "Proxy-Connection: close\r\n");
	sprintf(request + strlen(request), "\r\n");


	struct addrinfo hints, *response;
	int status;
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	status = getaddrinfo(hostname, port, &hints, &response);

	if (status != 0) return;

	int sock_fd = socket(response->ai_family, response->ai_socktype, response->ai_protocol);
	if (sock_fd < 0) {
		freeaddrinfo(response);
		close(client_fd);
		return;
	}
	if (connect(sock_fd, response->ai_addr, response->ai_addrlen) < 0) {
        freeaddrinfo(response);
        close(client_fd);
        return;
	}

	int bytes_sent = 0;
	bytes_sent = send(sock_fd, request, strlen(request), 0);
	if (bytes_sent < 0) {
		freeaddrinfo(response);
        close(client_fd);
        return;
	}

	char res_buffer[MAX_OBJECT_SIZE];
	int bytes_received;
	while ((bytes_received = recv(sock_fd, res_buffer, sizeof(res_buffer), 0)) > 0) {
		print_bytes((unsigned char *)res_buffer, bytes_received);
		send(client_fd, res_buffer, bytes_received, 0);
	}

	close(client_fd);
	close(sock_fd);
}


void test_parser() {
	int i;
	char method[16], hostname[64], port[8], path[64];

       	char *reqs[] = {
		"GET http://www.example.com/index.html HTTP/1.0\r\n"
		"Host: www.example.com\r\n"
		"User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0\r\n"
		"Accept-Language: en-US,en;q=0.5\r\n\r\n",

		"GET http://www.example.com:8080/index.html?foo=1&bar=2 HTTP/1.0\r\n"
		"Host: www.example.com:8080\r\n"
		"User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0\r\n"
		"Accept-Language: en-US,en;q=0.5\r\n\r\n",

		"GET http://localhost:1234/home.html HTTP/1.0\r\n"
		"Host: localhost:1234\r\n"
		"User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0\r\n"
		"Accept-Language: en-US,en;q=0.5\r\n\r\n",

		"GET http://www.example.com:8080/index.html HTTP/1.0\r\n",

		NULL
	};
	
	for (i = 0; reqs[i] != NULL; i++) {
		printf("Testing %s\n", reqs[i]);
		if (complete_request_received(reqs[i])) {
			printf("REQUEST COMPLETE\n");
			parse_request(reqs[i], method, hostname, port, path);
			printf("METHOD: %s\n", method);
			printf("HOSTNAME: %s\n", hostname);
			printf("PORT: %s\n", port);
			printf("PATH: %s\n", path);
		} else {
			printf("REQUEST INCOMPLETE\n");
		}
	}
}

void print_bytes(unsigned char *bytes, int byteslen) {
	int i, j, byteslen_adjusted;

	if (byteslen % 8) {
		byteslen_adjusted = ((byteslen / 8) + 1) * 8;
	} else {
		byteslen_adjusted = byteslen;
	}
	for (i = 0; i < byteslen_adjusted + 1; i++) {
		if (!(i % 8)) {
			if (i > 0) {
				for (j = i - 8; j < i; j++) {
					if (j >= byteslen_adjusted) {
						printf("  ");
					} else if (j >= byteslen) {
						printf("  ");
					} else if (bytes[j] >= '!' && bytes[j] <= '~') {
						printf(" %c", bytes[j]);
					} else {
						printf(" .");
					}
				}
			}
			if (i < byteslen_adjusted) {
				printf("\n%02X: ", i);
			}
		} else if (!(i % 4)) {
			printf(" ");
		}
		if (i >= byteslen_adjusted) {
			continue;
		} else if (i >= byteslen) {
			printf("   ");
		} else {
			printf("%02X ", bytes[i]);
		}
	}
	printf("\n");
	fflush(stdout);
}
